import assert from 'node:assert/strict';
import { test } from 'node:test';
import { looksGenerated } from '../../../runtime/graph/census.mjs';

test('generated markers count only in header comments, never in code (unfamiliar-repository regression)', () => {
  for (const t of ['// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x', '/**\n * @generated\n */\nexport const a = 1;', '# This file is autogenerated by pip-compile\nfoo==1', '<!-- auto-generated -->\n<div/>']) {
    assert.equal(looksGenerated(t), true, t);
  }
  for (const t of ['const x = { value: { autoGenerated: true } };', 'const s = "DO NOT EDIT";', 'if (filters?.autoGenerated) {}']) {
    assert.equal(looksGenerated(t), false, t);
  }
});
