import assert from 'node:assert/strict';
import { test } from 'node:test';
import { looksGenerated } from '../../../runtime/graph/census.mjs';

test('generated markers count only in header comments, never in code (unfamiliar-repository regression)', () => {
  for (const t of ['// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x', '/**\n * @generated\n */\nexport const a = 1;', '# This file is autogenerated by pip-compile\nfoo==1', '<!-- auto-generated -->\n<div/>']) {
    assert.equal(looksGenerated(t), true, t);
  }
  for (const t of ['const x = { value: { autoGenerated: true } };', 'const s = "DO NOT EDIT";', 'if (filters?.autoGenerated) {}']) {
    assert.equal(looksGenerated(t), false, t);
  }
});

test('markers in block comment bodies, docstrings, Haskell/OCaml/HTML comments and "automatically generated"', () => {
  for (const t of [
    '// This file was automatically generated by TanStack Router.\nexport const a = 1;',
    '/*\n   Generated by a tool. DO NOT EDIT\n*/\nint x;',
    '"""\nThis file is auto-generated.\n"""\nimport os',
    "\'\'\'\n@generated\n\'\'\'\nx = 1",
    '{-\n  autogenerated module\n-}\nmodule A where',
    '(* DO NOT EDIT *)\nlet x = 1',
    '<!--\n automatically generated\n-->\n<div/>',
  ]) assert.equal(looksGenerated(t), true, t);
  // First line of code ends the scan; markers after it do not count.
  assert.equal(looksGenerated('const a = 1;\n// DO NOT EDIT'), false);
  assert.equal(looksGenerated('/* license */\nconst a = 1;\n/* @generated */'), false);
});

test('census: .gen. names, minified files, native build output and e2e dirs', async () => {
  const { mkdtempSync, mkdirSync, writeFileSync, rmSync } = await import('node:fs');
  const { tmpdir } = await import('node:os');
  const { join } = await import('node:path');
  const { census } = await import('../../../runtime/graph/census.mjs');
  const root = mkdtempSync(join(tmpdir(), 'unknot-census-'));
  try {
    const put = (p, c) => { mkdirSync(join(root, p.split('/').slice(0, -1).join('/') || '.'), { recursive: true }); writeFileSync(join(root, p), c); };
    put('src/routeTree.gen.ts', 'export const a = 1;\n');
    put('src/min.js', `var a=${'1,'.repeat(600)}0;\n`);
    put('src/normal.js', 'var a = 1;\n');
    put('ios/App/App/public/main.js', 'x\n');
    put('android/app/src/main/assets/public/main.js', 'x\n');
    put('platforms/ios/www/main.js', 'x\n');
    put('e2e/login.ts', 'export {};\n');
    put('cypress/a.ts', 'export {};\n');
    put('playwright/a.ts', 'export {};\n');
    const { files } = census(root, { config: {} });
    const by = Object.fromEntries(files.map((f) => [f.path, f]));
    for (const p of ['src/routeTree.gen.ts', 'src/min.js', 'ios/App/App/public/main.js', 'android/app/src/main/assets/public/main.js', 'platforms/ios/www/main.js']) assert.equal(by[p].kind, 'generated', p);
    assert.equal(by['src/normal.js'].kind, 'source');
    for (const p of ['e2e/login.ts', 'cypress/a.ts', 'playwright/a.ts']) assert.equal(by[p].is_test, true, p);
  } finally { rmSync(root, { recursive: true, force: true }); }
});
