// Repository census (spec §9.4 step 1). Every file gets a kind before any adapter sees it:
// secrets are never read, symlinks are never followed, binaries and vendored or
// generated code are recorded but not analysed as ordinary editable source (spec §2.2).

import { closeSync, lstatSync, openSync, readdirSync, readFileSync, readSync } from 'node:fs';
import { extname, join } from 'node:path';
import { sha256 } from '../core/canonical.mjs';
import { inScope, matchAny } from '../core/glob.mjs';
import { isSecretPath } from '../core/paths.mjs';
import { pathGlobs } from '../core/scope.mjs';

// Ownership files at fixed root locations: read whatever the scope, so a narrow scope still
// gets its owners. Flagged `context`: never counted as in-scope files or modules.
export const CONTEXT_FILES = ['CODEOWNERS', '.github/CODEOWNERS', 'docs/CODEOWNERS', '.gitlab/CODEOWNERS'];
import { blobIds, git, isRepo, listFiles } from '../apply/git.mjs';

const LANGUAGES = {
  '.js': 'javascript', '.mjs': 'javascript', '.cjs': 'javascript', '.jsx': 'javascript',
  '.ts': 'typescript', '.mts': 'typescript', '.cts': 'typescript', '.tsx': 'typescript',
  '.py': 'python', '.go': 'go', '.java': 'java', '.kt': 'kotlin', '.kts': 'kotlin', '.scala': 'scala',
  '.cs': 'csharp', '.rs': 'rust', '.rb': 'ruby', '.php': 'php', '.swift': 'swift',
  '.c': 'c', '.h': 'c', '.cc': 'cpp', '.cpp': 'cpp', '.cxx': 'cpp', '.hpp': 'cpp', '.hh': 'cpp',
  '.vue': 'vue', '.svelte': 'svelte', '.sql': 'sql', '.tf': 'hcl', '.hcl': 'hcl', '.bicep': 'bicep',
  '.sh': 'shell', '.bash': 'shell', '.zsh': 'shell', '.ps1': 'powershell',
  '.yaml': 'yaml', '.yml': 'yaml', '.json': 'json', '.toml': 'toml', '.xml': 'xml', '.ini': 'ini',
  '.md': 'markdown', '.rst': 'rst', '.proto': 'protobuf', '.graphql': 'graphql', '.gql': 'graphql',
  '.prisma': 'prisma', '.dockerfile': 'dockerfile',
};
const CODE = new Set(['javascript', 'typescript', 'python', 'go', 'java', 'kotlin', 'scala', 'csharp', 'rust', 'ruby', 'php', 'swift', 'c', 'cpp', 'vue', 'svelte', 'shell', 'powershell']);
const CONFIG = new Set(['yaml', 'json', 'toml', 'xml', 'ini', 'hcl', 'bicep', 'sql', 'prisma', 'protobuf', 'graphql', 'dockerfile']);
const BINARY_EXT = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.ico', '.pdf', '.zip', '.gz', '.tgz', '.jar', '.war', '.class', '.so', '.dylib', '.dll', '.exe', '.wasm', '.woff', '.woff2', '.ttf', '.otf', '.mp4', '.mp3', '.mov', '.sqlite', '.db', '.bin', '.pyc', '.o', '.a']);
const VENDORED = ['**/vendor/**', '**/third_party/**', '**/third-party/**', '**/node_modules/**', '**/bower_components/**', '.yarn/**', '**/Pods/**'];
const GENERATED = ['**/dist/**', '**/build/**', '**/out/**', '**/target/**', '**/.next/**', '**/coverage/**', '**/*.min.js', '**/*.min.css', '**/*.map', '**/*.pb.go', '**/*_pb2.py', '**/*_pb2_grpc.py', '**/*.pb.ts', '**/*.generated.*', '**/*.gen.*', '**/ios/App/App/public/**', '**/android/app/src/main/assets/public/**', '**/platforms/*/www/**', '**/*.g.dart', '**/*.g.cs', '**/generated/**', '**/__generated__/**', '**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml', '**/poetry.lock', '**/Cargo.lock', '**/go.sum', '**/composer.lock', '**/Gemfile.lock'];
const TEST = ['**/*.test.*', '**/*.spec.*', '**/*.tests.*', '**/*_tests.*', '**/*-tests.*', '**/__tests__/**', '**/__mocks__/**', '**/__*_mocks__/**', '**/test/**', '**/tests/**', '**/spec/**', '**/e2e/**', '**/cypress/**', '**/playwright/**', '**/*_test.go', '**/*_test.py', '**/test_*.py', '**/*Test.java', '**/*Tests.cs', '**/*_spec.rb', '**/conftest.py'];
const GENERATED_MARK = /@generated|DO NOT EDIT|Code generated by|\bauto-?generated\b|automatically generated|This file (was|is) (auto-?)?generated/i;
const BLOCKS = [['/*', '*/'], ['"""', '"""'], ["'''", "'''"], ['{-', '-}'], ['(*', '*)'], ['<!--', '-->']];
const LINE_COMMENT = /^\s*(\/\/|#(?!\[)|--|;|%|')/;

/**
 * A generated-file marker counts only in comment text near the top (first 40 lines), tracking
 * block comments and docstrings, and stops at the first line of code. Searching the raw text
 * classified ordinary code as generated because a field was named `autoGenerated`.
 */
export function looksGenerated(text) {
  const lines = text.split('\n', 40);
  let close = null;
  const comment = [];
  for (const raw of lines) {
    let line = raw;
    if (close === null && !line.trim()) continue;
    let sawCode = false;
    while (line.length) {
      if (close !== null) {
        const end = line.indexOf(close);
        if (end === -1) { comment.push(line); line = ''; } else { comment.push(line.slice(0, end)); line = line.slice(end + close.length); close = null; }
        continue;
      }
      const t = line.trimStart();
      if (!t) break;
      const blk = BLOCKS.find(([o]) => t.startsWith(o));
      if (blk) { close = blk[1]; line = t.slice(blk[0].length); continue; }
      if (LINE_COMMENT.test(t)) { comment.push(t); line = ''; continue; }
      sawCode = true;
      break;
    }
    if (sawCode) break;
  }
  return GENERATED_MARK.test(comment.join('\n'));
}

// .NET keeps tests in projects, not in files named *Tests.cs: a directory named like a test
// project (Shop.Orders.Tests, Shop.UnitTests, Shop.Specs, ...Tests) holds only test code.
const TEST_DIR = /(^|\/)[^/]*(Tests|\.Test|\.Specs?)\//;
// A project that references a test framework, says it is one, or is named like one is a test
// project wherever it sits (the test SDK often arrives through shared build files instead).
const TEST_SDK = /Microsoft\.NET\.Test\.Sdk|xunit|NUnit|MSTest|<IsTestProject>\s*true/i;
const TEST_PROJECT_NAME = /(Tests?|Specs?)\.(cs|fs|vb)proj$/i;
const PROJECT = /\.(cs|fs|vb)proj$/i;
const dirOf = (path) => (path.includes('/') ? path.slice(0, path.lastIndexOf('/')) : '');

/**
 * Directories whose nearest `.csproj` references a test framework. Each project file is
 * read once, however many sources sit beneath it.
 */
function testProjectDirs(root, paths) {
  const found = new Set();
  for (const p of paths) {
    if (!PROJECT.test(p)) continue;
    if (TEST_PROJECT_NAME.test(p)) {
      found.add(dirOf(p));
      continue;
    }
    try {
      if (TEST_SDK.test(readFileSync(join(root, p), 'utf8'))) found.add(dirOf(p));
    } catch {
      // unreadable project file: its directory is not known to be a test project
    }
  }
  return found;
}

/** Whether `path` lies under a directory of `dirs` with no nearer project directory in between. */
function underTestProject(path, dirs, projectDirs) {
  for (let d = dirOf(path); ; d = dirOf(d)) {
    if (dirs.has(d)) return true;
    if (projectDirs.has(d) || !d) return false;
  }
}

/** Test files and test directories, by path (the census's own rule). */
export const isTestFile = (path) => matchAny(path, TEST) || TEST_DIR.test(path);
/** Test code: a test path in a programming language (not a spec document or fixture data). */
export const isTestCode = (path) => isTestFile(path) && CODE.has(languageOf(path));

export function languageOf(path) {
  const base = path.split('/').pop();
  if (/^Dockerfile(\..+)?$|\.dockerfile$/i.test(base)) return 'dockerfile';
  if (base === 'Makefile' || base === 'GNUmakefile') return 'make';
  if (base === 'Jenkinsfile') return 'groovy';
  return LANGUAGES[extname(base).toLowerCase()] ?? null;
}

function head(path, bytes = 8192) {
  let fd;
  try {
    fd = openSync(path, 'r');
    const buf = Buffer.alloc(bytes);
    const n = readSync(fd, buf, 0, bytes, 0);
    return buf.subarray(0, n);
  } catch {
    return null;
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

function attributeRules(root) {
  try {
    const text = readFileSync(join(root, '.gitattributes'), 'utf8');
    const generated = [];
    const vendored = [];
    for (const line of text.split('\n')) {
      const [pat, ...attrs] = line.trim().split(/\s+/);
      if (!pat || pat.startsWith('#')) continue;
      const glob = pat.includes('/') ? pat.replace(/^\//, '') : `**/${pat}`;
      if (attrs.some((a) => a === 'linguist-generated' || a === 'linguist-generated=true')) generated.push(glob);
      if (attrs.some((a) => a === 'linguist-vendored' || a === 'linguist-vendored=true')) vendored.push(glob);
    }
    return { generated, vendored };
  } catch {
    return { generated: [], vendored: [] };
  }
}

function walk(root, dir = '', out = []) {
  for (const e of readdirSync(join(root, dir), { withFileTypes: true })) {
    if (e.name === '.git' || e.name === '.unknot' || e.name === 'node_modules' || e.name === '.claude') continue;
    const rel = dir ? `${dir}/${e.name}` : e.name;
    if (e.isDirectory()) walk(root, rel, out);
    else out.push(rel);
  }
  return out;
}

/**
 * @param {string} root
 * @param {{config: object, scope?: string[]}} opts `scope` narrows to path prefixes/globs
 * @returns {{files: object[], repo: boolean, commit: string|null, byKind: object}}
 */
export function census(root, { config, scope = [] } = {}) {
  const repo = isRepo(root);
  const paths = repo ? listFiles(root) : walk(root).sort();
  const blobs = repo ? blobIds(root) : new Map();
  const modified = new Set(repo ? git(root, ['diff', '--name-only', '-z'], { check: false }).stdout.split('\0').filter(Boolean) : []);
  const attrs = attributeRules(root);
  const generatedGlobs = [...GENERATED, ...(config?.generated_paths ?? []), ...attrs.generated];
  const vendoredGlobs = [...VENDORED, ...attrs.vendored];
  const maxBytes = config?.limits?.max_file_bytes ?? 2 * 1024 * 1024;
  const scopeGlobs = pathGlobs(scope) ?? [];
  const csproj = paths.filter((p) => PROJECT.test(p));
  const testProjects = csproj.length ? testProjectDirs(root, paths) : new Set();
  const projectDirs = new Set(csproj.map(dirOf));
  const files = [];
  const byKind = {};
  for (const path of paths) {
    if (path.startsWith('.unknot/') || path.startsWith('.claude/')) continue;
    if (config?.scope && !inScope(path, config.scope)) continue;
    const context = Boolean(scopeGlobs?.length) && CONTEXT_FILES.includes(path) && !matchAny(path, scopeGlobs);
    if (scopeGlobs?.length && !context && !matchAny(path, scopeGlobs)) continue;
    const abs = join(root, path);
    let st;
    try {
      st = lstatSync(abs);
    } catch {
      continue;
    }
    const entry = { path, size: st.size, language: languageOf(path), kind: 'other', blob: null, is_test: isTestFile(path) || (testProjects.size > 0 && underTestProject(path, testProjects, projectDirs)), too_large: st.size > maxBytes, ...(context && { context: true }) };
    if (st.isSymbolicLink()) entry.kind = 'symlink';
    else if (!st.isFile()) continue;
    else if (isSecretPath(path)) entry.kind = 'secret';
    else if (BINARY_EXT.has(extname(path).toLowerCase())) entry.kind = 'binary';
    else if (matchAny(path, vendoredGlobs)) entry.kind = 'vendored';
    else if (matchAny(path, generatedGlobs)) entry.kind = 'generated';
    else {
      const h = head(abs, 4096);
      if (h && h.includes(0)) entry.kind = 'binary';
      else if (h && /\.(m?js|cjs|css)$/i.test(path) && h.toString('utf8').split('\n').some((l) => l.length > 1000)) entry.kind = 'generated';
      else if (h && looksGenerated(h.subarray(0, 2048).toString('utf8'))) entry.kind = 'generated';
      else if (entry.is_test && CODE.has(entry.language)) entry.kind = 'test';
      else if (CODE.has(entry.language)) entry.kind = 'source';
      else if (['markdown', 'rst'].includes(entry.language) || path.startsWith('docs/')) entry.kind = 'doc';
      else if (CONFIG.has(entry.language) || entry.language === 'make' || entry.language === 'groovy') entry.kind = 'config';
    }
    if (blobs.has(path) && !modified.has(path)) entry.blob = `git:${blobs.get(path)}`;
    files.push(entry);
    if (!context) byKind[entry.kind] = (byKind[entry.kind] ?? 0) + 1;
  }
  const commit = repo ? git(root, ['rev-parse', 'HEAD'], { check: false }).stdout.trim() || null : null;
  return { files, repo, commit, byKind };
}

/** Read a census entry's text for an adapter, filling in its content blob id. */
export function readEntry(root, entry) {
  if (['secret', 'symlink', 'binary'].includes(entry.kind) || entry.too_large) return null;
  const buf = readFileSync(join(root, entry.path));
  if (!entry.blob) entry.blob = `sha256:${sha256(buf)}`;
  return buf.toString('utf8');
}

/** Whether an entry's content is analysed as ordinary source by adapters. */
export const analysable = (entry) => ['source', 'test', 'config', 'doc', 'other'].includes(entry.kind) && !entry.too_large;
