// Repository census (spec §9.4 step 1). Every file gets a kind before any adapter sees it:
// secrets are never read, symlinks are never followed, binaries and vendored or
// generated code are recorded but not analysed as ordinary editable source (spec §2.2).

import { closeSync, lstatSync, openSync, readdirSync, readFileSync, readSync } from 'node:fs';
import { extname, join } from 'node:path';
import { sha256 } from '../core/canonical.mjs';
import { inScope, matchAny } from '../core/glob.mjs';
import { isSecretPath } from '../core/paths.mjs';
import { blobIds, git, isRepo, listFiles } from '../apply/git.mjs';

const LANGUAGES = {
  '.js': 'javascript', '.mjs': 'javascript', '.cjs': 'javascript', '.jsx': 'javascript',
  '.ts': 'typescript', '.mts': 'typescript', '.cts': 'typescript', '.tsx': 'typescript',
  '.py': 'python', '.go': 'go', '.java': 'java', '.kt': 'kotlin', '.kts': 'kotlin', '.scala': 'scala',
  '.cs': 'csharp', '.rs': 'rust', '.rb': 'ruby', '.php': 'php', '.swift': 'swift',
  '.c': 'c', '.h': 'c', '.cc': 'cpp', '.cpp': 'cpp', '.cxx': 'cpp', '.hpp': 'cpp', '.hh': 'cpp',
  '.vue': 'vue', '.svelte': 'svelte', '.sql': 'sql', '.tf': 'hcl', '.hcl': 'hcl', '.bicep': 'bicep',
  '.sh': 'shell', '.bash': 'shell', '.zsh': 'shell', '.ps1': 'powershell',
  '.yaml': 'yaml', '.yml': 'yaml', '.json': 'json', '.toml': 'toml', '.xml': 'xml', '.ini': 'ini',
  '.md': 'markdown', '.rst': 'rst', '.proto': 'protobuf', '.graphql': 'graphql', '.gql': 'graphql',
  '.prisma': 'prisma', '.dockerfile': 'dockerfile',
};
const CODE = new Set(['javascript', 'typescript', 'python', 'go', 'java', 'kotlin', 'scala', 'csharp', 'rust', 'ruby', 'php', 'swift', 'c', 'cpp', 'vue', 'svelte', 'shell', 'powershell']);
const CONFIG = new Set(['yaml', 'json', 'toml', 'xml', 'ini', 'hcl', 'bicep', 'sql', 'prisma', 'protobuf', 'graphql', 'dockerfile']);
const BINARY_EXT = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.ico', '.pdf', '.zip', '.gz', '.tgz', '.jar', '.war', '.class', '.so', '.dylib', '.dll', '.exe', '.wasm', '.woff', '.woff2', '.ttf', '.otf', '.mp4', '.mp3', '.mov', '.sqlite', '.db', '.bin', '.pyc', '.o', '.a']);
const VENDORED = ['**/vendor/**', '**/third_party/**', '**/third-party/**', '**/node_modules/**', '**/bower_components/**', '.yarn/**', '**/Pods/**'];
const GENERATED = ['**/dist/**', '**/build/**', '**/out/**', '**/target/**', '**/.next/**', '**/coverage/**', '**/*.min.js', '**/*.min.css', '**/*.map', '**/*.pb.go', '**/*_pb2.py', '**/*_pb2_grpc.py', '**/*.pb.ts', '**/*.generated.*', '**/*.g.dart', '**/*.g.cs', '**/generated/**', '**/__generated__/**', '**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml', '**/poetry.lock', '**/Cargo.lock', '**/go.sum', '**/composer.lock', '**/Gemfile.lock'];
const TEST = ['**/*.test.*', '**/*.spec.*', '**/*.tests.*', '**/*_tests.*', '**/*-tests.*', '**/__tests__/**', '**/__mocks__/**', '**/__*_mocks__/**', '**/test/**', '**/tests/**', '**/spec/**', '**/*_test.go', '**/*_test.py', '**/test_*.py', '**/*Test.java', '**/*Tests.cs', '**/*_spec.rb', '**/conftest.py'];
const GENERATED_MARK = /@generated|DO NOT EDIT|Code generated by|\bauto-?generated\b|This file (was|is) (auto-?)?generated/i;
const COMMENT_LINE = /^\s*(\/\/|\/\*|\*|#|<!--|--|;|%|')/;

/**
 * A generated-file marker counts only in a comment near the top. Searching the raw text
 * classified ordinary code as generated (and skipped it) because a field was named
 * `autoGenerated` (found on an unfamiliar repository).
 */
export function looksGenerated(text) {
  const header = text.split('\n', 40).filter((l) => COMMENT_LINE.test(l)).join('\n');
  return GENERATED_MARK.test(header);
}

export function languageOf(path) {
  const base = path.split('/').pop();
  if (/^Dockerfile(\..+)?$|\.dockerfile$/i.test(base)) return 'dockerfile';
  if (base === 'Makefile' || base === 'GNUmakefile') return 'make';
  if (base === 'Jenkinsfile') return 'groovy';
  return LANGUAGES[extname(base).toLowerCase()] ?? null;
}

function head(path, bytes = 8192) {
  let fd;
  try {
    fd = openSync(path, 'r');
    const buf = Buffer.alloc(bytes);
    const n = readSync(fd, buf, 0, bytes, 0);
    return buf.subarray(0, n);
  } catch {
    return null;
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

function attributeRules(root) {
  try {
    const text = readFileSync(join(root, '.gitattributes'), 'utf8');
    const generated = [];
    const vendored = [];
    for (const line of text.split('\n')) {
      const [pat, ...attrs] = line.trim().split(/\s+/);
      if (!pat || pat.startsWith('#')) continue;
      const glob = pat.includes('/') ? pat.replace(/^\//, '') : `**/${pat}`;
      if (attrs.some((a) => a === 'linguist-generated' || a === 'linguist-generated=true')) generated.push(glob);
      if (attrs.some((a) => a === 'linguist-vendored' || a === 'linguist-vendored=true')) vendored.push(glob);
    }
    return { generated, vendored };
  } catch {
    return { generated: [], vendored: [] };
  }
}

function walk(root, dir = '', out = []) {
  for (const e of readdirSync(join(root, dir), { withFileTypes: true })) {
    if (e.name === '.git' || e.name === '.unknot' || e.name === 'node_modules' || e.name === '.claude') continue;
    const rel = dir ? `${dir}/${e.name}` : e.name;
    if (e.isDirectory()) walk(root, rel, out);
    else out.push(rel);
  }
  return out;
}

/**
 * @param {string} root
 * @param {{config: object, scope?: string[]}} opts `scope` narrows to path prefixes/globs
 * @returns {{files: object[], repo: boolean, commit: string|null, byKind: object}}
 */
export function census(root, { config, scope = [] } = {}) {
  const repo = isRepo(root);
  const paths = repo ? listFiles(root) : walk(root).sort();
  const blobs = repo ? blobIds(root) : new Map();
  const modified = new Set(repo ? git(root, ['diff', '--name-only', '-z'], { check: false }).stdout.split('\0').filter(Boolean) : []);
  const attrs = attributeRules(root);
  const generatedGlobs = [...GENERATED, ...(config?.generated_paths ?? []), ...attrs.generated];
  const vendoredGlobs = [...VENDORED, ...attrs.vendored];
  const maxBytes = config?.limits?.max_file_bytes ?? 2 * 1024 * 1024;
  const scopeGlobs = scope.map((s) => (/[*?[{]/.test(s) ? s : `${s.replace(/\/$/, '')}/**`));
  const files = [];
  const byKind = {};
  for (const path of paths) {
    if (path.startsWith('.unknot/') || path.startsWith('.claude/')) continue;
    if (config?.scope && !inScope(path, config.scope)) continue;
    if (scopeGlobs.length && !matchAny(path, scopeGlobs)) continue;
    const abs = join(root, path);
    let st;
    try {
      st = lstatSync(abs);
    } catch {
      continue;
    }
    const entry = { path, size: st.size, language: languageOf(path), kind: 'other', blob: null, is_test: matchAny(path, TEST), too_large: st.size > maxBytes };
    if (st.isSymbolicLink()) entry.kind = 'symlink';
    else if (!st.isFile()) continue;
    else if (isSecretPath(path)) entry.kind = 'secret';
    else if (BINARY_EXT.has(extname(path).toLowerCase())) entry.kind = 'binary';
    else if (matchAny(path, vendoredGlobs)) entry.kind = 'vendored';
    else if (matchAny(path, generatedGlobs)) entry.kind = 'generated';
    else {
      const h = head(abs, 4096);
      if (h && h.includes(0)) entry.kind = 'binary';
      else if (h && looksGenerated(h.subarray(0, 2048).toString('utf8'))) entry.kind = 'generated';
      else if (entry.is_test && CODE.has(entry.language)) entry.kind = 'test';
      else if (CODE.has(entry.language)) entry.kind = 'source';
      else if (['markdown', 'rst'].includes(entry.language) || path.startsWith('docs/')) entry.kind = 'doc';
      else if (CONFIG.has(entry.language) || entry.language === 'make' || entry.language === 'groovy') entry.kind = 'config';
    }
    if (blobs.has(path) && !modified.has(path)) entry.blob = `git:${blobs.get(path)}`;
    files.push(entry);
    byKind[entry.kind] = (byKind[entry.kind] ?? 0) + 1;
  }
  const commit = repo ? git(root, ['rev-parse', 'HEAD'], { check: false }).stdout.trim() || null : null;
  return { files, repo, commit, byKind };
}

/** Read a census entry's text for an adapter, filling in its content blob id. */
export function readEntry(root, entry) {
  if (['secret', 'symlink', 'binary'].includes(entry.kind) || entry.too_large) return null;
  const buf = readFileSync(join(root, entry.path));
  if (!entry.blob) entry.blob = `sha256:${sha256(buf)}`;
  return buf.toString('utf8');
}

/** Whether an entry's content is analysed as ordinary source by adapters. */
export const analysable = (entry) => ['source', 'test', 'config', 'doc', 'other'].includes(entry.kind) && !entry.too_large;
