import test from 'node:test';
import assert from 'node:assert/strict';
import { splitStatements, tokenize } from '../../../../adapters/database/sql/lexer.mjs';
import { parseSql, extractTables } from '../../../../adapters/database/sql/parser.mjs';
import { prng } from './helpers.mjs';

const one = (sql, opts) => parseSql(sql, opts)[0];

// ------------------------------------------------------------------ lexer / splitter

test('splitter: dollar-quoted bodies keep their semicolons', () => {
  const s = splitStatements("CREATE FUNCTION f() RETURNS int AS $$ BEGIN; SELECT 1; END $$ LANGUAGE plpgsql; SELECT 2;");
  assert.equal(s.length, 2);
  assert.match(s[0].text, /LANGUAGE plpgsql$/);
});

test('splitter: tagged dollar quotes', () => {
  const s = splitStatements('DO $body$ BEGIN PERFORM 1; END $body$; SELECT 1;');
  assert.equal(s.length, 2);
});

test('splitter: E-strings with escaped quotes, and doubled quotes', () => {
  const s = splitStatements("SELECT E'it\\'s; ok'; SELECT 'a''b;c';");
  assert.equal(s.length, 2);
});

test('splitter: quoted identifiers contain semicolons and quotes', () => {
  const s = splitStatements('SELECT "a;b" FROM "t""x"; SELECT `c;d` FROM t;', { dialect: 'mysql' });
  assert.equal(s.length, 2);
  assert.equal(tokenize('"t""x"')[0].v, 't"x');
});

test('splitter: bracket identifiers in T-SQL/SQLite only', () => {
  assert.equal(tokenize('[my col]', { dialect: 'tsql' })[0].t, 'qident');
  assert.equal(tokenize('int[]', { dialect: 'postgresql' }).length, 3);
});

test('splitter: line and nested block comments', () => {
  const s = splitStatements('-- a; b\nSELECT 1; /* x; /* y; */ z; */ SELECT 2');
  assert.equal(s.length, 2);
  assert.equal(s[1].line, 2);
});

test('splitter: MySQL DELIMITER scripts', () => {
  const sql = 'DELIMITER //\nCREATE TRIGGER t BEFORE INSERT ON a FOR EACH ROW BEGIN SET @x = 1; SET @y = 2; END//\nDELIMITER ;\nSELECT 1;';
  const s = splitStatements(sql, { dialect: 'mysql' });
  assert.equal(s.length, 2);
  assert.match(s[0].text, /SET @y = 2; END$/);
});

test('splitter: GO batch separators', () => {
  const s = splitStatements('SELECT 1\nGO\nSELECT 2\nGO 5\n', { dialect: 'tsql' });
  assert.equal(s.length, 2);
});

test('splitter: SQLite trigger bodies stay whole', () => {
  const sql = 'CREATE TRIGGER tr AFTER INSERT ON a BEGIN UPDATE b SET x = 1; DELETE FROM c; END; SELECT 1;';
  const s = splitStatements(sql, { dialect: 'sqlite' });
  assert.equal(s.length, 2);
});

test('splitter: unterminated constructs do not throw', () => {
  for (const sql of ["SELECT 'abc", 'SELECT "abc', '/* never closed', '$$ open', 'SELECT `x']) {
    assert.doesNotThrow(() => splitStatements(sql));
  }
});

// ------------------------------------------------------------------ CREATE TABLE

test('create table: columns, types, defaults, volatility', () => {
  const st = one(`CREATE TABLE IF NOT EXISTS public.t (
    id bigserial PRIMARY KEY,
    name character varying(255) NOT NULL DEFAULT 'x',
    amount numeric(10, 2) DEFAULT 0,
    at timestamp with time zone DEFAULT now(),
    token uuid DEFAULT gen_random_uuid(),
    tags text[] DEFAULT '{}'::text[],
    g int GENERATED ALWAYS AS (amount * 2) STORED,
    ident bigint GENERATED BY DEFAULT AS IDENTITY,
    c text COLLATE "C"
  )`);
  assert.equal(st.kind, 'create_table');
  assert.equal(st.if_not_exists, true);
  assert.deepEqual(st.table, { schema: 'public', name: 't', db: null });
  const col = Object.fromEntries(st.columns.map((c) => [c.name, c]));
  assert.equal(col.id.identity, 'serial');
  assert.equal(col.id.nullable, false);
  assert.equal(col.name.type, 'character varying(255)');
  assert.equal(col.name.default.expr, "'x'");
  assert.equal(col.name.default.kind, 'literal');
  assert.equal(col.amount.type, 'numeric(10,2)');
  assert.equal(col.at.type, 'timestamp with time zone');
  assert.equal(col.at.default.stable_function, true);
  assert.equal(col.at.default.volatile, false);
  assert.equal(col.token.default.volatile, true);
  assert.equal(col.tags.type, 'text[]');
  assert.deepEqual(col.g.generated, { expr: 'amount * 2', stored: true });
  assert.equal(col.ident.identity, 'by default');
  assert.equal(col.c.collation, 'C');
});

test('create table: inline and table constraints', () => {
  const st = one(`CREATE TABLE o (
    id int PRIMARY KEY,
    cid int NOT NULL REFERENCES customers (id) ON DELETE SET NULL ON UPDATE CASCADE,
    sku text UNIQUE,
    qty int CHECK (qty > 0),
    CONSTRAINT o_uq UNIQUE (cid, sku),
    FOREIGN KEY (cid) REFERENCES c2 (id) ON DELETE CASCADE NOT VALID,
    CHECK (qty < 1000)
  )`);
  const kinds = st.constraints.map((k) => k.kind).sort();
  assert.deepEqual(kinds, ['check', 'check', 'foreign_key', 'foreign_key', 'primary_key', 'unique', 'unique']);
  const fk = st.constraints.find((k) => k.kind === 'foreign_key' && k.ref_table.name === 'customers');
  assert.equal(fk.on_delete, 'SET NULL');
  assert.equal(fk.on_update, 'CASCADE');
  const fk2 = st.constraints.find((k) => k.ref_table?.name === 'c2');
  assert.equal(fk2.on_delete, 'CASCADE');
  assert.equal(fk2.not_valid, true);
  assert.equal(st.constraints.find((k) => k.name === 'o_uq').columns.join(), 'cid,sku');
});

test('create table: partitioning, LIKE, partition of, CTAS', () => {
  assert.deepEqual(one('CREATE TABLE m (ts timestamptz) PARTITION BY RANGE (ts)').partition_by, { type: 'RANGE', columns: ['ts'] });
  assert.equal(one('CREATE TABLE a (LIKE b INCLUDING ALL)').like[0].name, 'b');
  assert.equal(one("CREATE TABLE m1 PARTITION OF m FOR VALUES FROM ('2024-01-01') TO ('2024-02-01')").partition_of.name, 'm');
  const ctas = one('CREATE TABLE s AS SELECT * FROM src JOIN other o ON o.id = src.id');
  assert.equal(ctas.as_select, true);
  assert.deepEqual(ctas.source_tables.map((t) => t.name).sort(), ['other', 'src']);
});

test('create table: MySQL options and inline keys', () => {
  const st = one('CREATE TABLE `t` (`id` int AUTO_INCREMENT PRIMARY KEY, `n` varchar(10) NOT NULL, KEY `idx_n` (`n`), UNIQUE KEY uq (`id`,`n`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4', { dialect: 'mysql' });
  assert.equal(st.columns[0].identity, 'auto_increment');
  assert.equal(st.indexes[0].name, 'idx_n');
  assert.equal(st.constraints.some((k) => k.kind === 'unique'), true);
});

test('identifiers fold to lower case unless quoted', () => {
  const st = one('CREATE TABLE Public."MixedCase" (ID int)');
  assert.equal(st.table.schema, 'public');
  assert.equal(st.table.name, 'MixedCase');
  assert.equal(st.columns[0].name, 'id');
});

// ------------------------------------------------------------------ ALTER TABLE

test('alter table: PostgreSQL action vocabulary', () => {
  const cases = [
    ['ALTER TABLE t ADD COLUMN IF NOT EXISTS c int DEFAULT 1', 'add_column'],
    ['ALTER TABLE t DROP COLUMN IF EXISTS c CASCADE', 'drop_column'],
    ['ALTER TABLE t RENAME COLUMN a TO b', 'rename_column'],
    ['ALTER TABLE t RENAME TO u', 'rename_table'],
    ['ALTER TABLE t ALTER COLUMN c SET DATA TYPE bigint USING c::bigint', 'alter_column_type'],
    ['ALTER TABLE t ALTER COLUMN c TYPE varchar(10)', 'alter_column_type'],
    ['ALTER TABLE t ALTER COLUMN c SET DEFAULT 5', 'set_default'],
    ['ALTER TABLE t ALTER COLUMN c DROP DEFAULT', 'drop_default'],
    ['ALTER TABLE t ALTER COLUMN c SET NOT NULL', 'set_not_null'],
    ['ALTER TABLE t ALTER COLUMN c DROP NOT NULL', 'drop_not_null'],
    ['ALTER TABLE t ADD CONSTRAINT k CHECK (a > 0) NOT VALID', 'add_constraint'],
    ['ALTER TABLE t VALIDATE CONSTRAINT k', 'validate_constraint'],
    ['ALTER TABLE t DROP CONSTRAINT k', 'drop_constraint'],
    ['ALTER TABLE t SET TABLESPACE fast', 'set_tablespace'],
    ['ALTER TABLE p ATTACH PARTITION c FOR VALUES IN (1)', 'attach_partition'],
    ['ALTER TABLE p DETACH PARTITION c CONCURRENTLY', 'detach_partition'],
    ['ALTER TABLE t SET LOGGED', 'set_logged'],
    ['ALTER TABLE t SET UNLOGGED', 'set_unlogged'],
    ['ALTER TABLE t ENABLE ROW LEVEL SECURITY', 'row_level_security'],
    ['ALTER TABLE ONLY t OWNER TO bob', 'owner_to'],
  ];
  for (const [sql, action] of cases) {
    const st = one(sql);
    assert.equal(st.kind, 'alter_table', sql);
    assert.equal(st.actions[0].action, action, sql);
  }
  const t = one('ALTER TABLE t ALTER COLUMN c TYPE bigint USING c::bigint').actions[0];
  assert.equal(t.type, 'bigint');
  assert.equal(t.using, 'c::bigint');
  assert.equal(one('ALTER TABLE p DETACH PARTITION c CONCURRENTLY').actions[0].concurrently, true);
  assert.equal(one('ALTER TABLE t ADD CONSTRAINT k CHECK (a > 0) NOT VALID').actions[0].constraint.not_valid, true);
  assert.equal(one('ALTER TABLE t ADD CONSTRAINT k UNIQUE USING INDEX ix').actions[0].constraint.using_index, 'ix');
});

test('alter table: multiple comma-separated actions', () => {
  const st = one('ALTER TABLE t ADD COLUMN a int, ADD COLUMN b text NOT NULL DEFAULT \'\', DROP COLUMN c');
  assert.deepEqual(st.actions.map((a) => a.action), ['add_column', 'add_column', 'drop_column']);
  assert.equal(st.actions[1].column.nullable, false);
});

test('alter table: MySQL ALGORITHM/LOCK, MODIFY and CHANGE', () => {
  const st = one('ALTER TABLE t ADD COLUMN c int AFTER a, ALGORITHM=INPLACE, LOCK=NONE', { dialect: 'mysql' });
  assert.equal(st.algorithm, 'INPLACE');
  assert.equal(st.lock, 'NONE');
  assert.equal(st.actions[0].column.position, 'after a');
  assert.equal(one('ALTER TABLE t MODIFY COLUMN c varchar(10) NOT NULL', { dialect: 'mysql' }).actions[0].action, 'modify_column');
  const ch = one('ALTER TABLE t CHANGE COLUMN a b bigint', { dialect: 'mysql' }).actions[0];
  assert.equal(ch.action, 'change_column');
  assert.equal(ch.from, 'a');
  assert.equal(ch.column.name, 'b');
});

// ------------------------------------------------------------------ indexes, views, others

test('indexes', () => {
  const ix = one('CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS ix ON ONLY s.t USING gin (lower(a), b DESC) INCLUDE (c) WHERE d > 0');
  assert.equal(ix.kind, 'create_index');
  assert.equal(ix.unique, true);
  assert.equal(ix.concurrently, true);
  assert.equal(ix.if_not_exists, true);
  assert.equal(ix.method, 'gin');
  assert.equal(ix.where, 'd > 0');
  assert.equal(ix.table.schema, 's');
  assert.equal(ix.columns.length, 2);
  assert.deepEqual(ix.include, ['c']);
  const d = one('DROP INDEX CONCURRENTLY IF EXISTS a, b');
  assert.equal(d.concurrently, true);
  assert.equal(d.indexes.length, 2);
  const r = one('REINDEX (VERBOSE) TABLE CONCURRENTLY t');
  assert.deepEqual([r.kind, r.concurrently, r.target_type, r.name.name], ['reindex', true, 'table', 't']);
  const my = one('CREATE INDEX i ON t (a) ALGORITHM=INPLACE LOCK=NONE', { dialect: 'mysql' });
  assert.equal(my.algorithm, 'INPLACE');
  assert.equal(my.lock, 'NONE');
});

test('views, materialized views and refresh', () => {
  const v = one('CREATE OR REPLACE MATERIALIZED VIEW IF NOT EXISTS mv AS SELECT * FROM a JOIN b ON a.id = b.id WITH NO DATA');
  assert.equal(v.kind, 'create_view');
  assert.equal(v.materialized, true);
  assert.equal(v.with_no_data, true);
  assert.deepEqual(v.sources.map((s) => s.name).sort(), ['a', 'b']);
  assert.equal(one('DROP MATERIALIZED VIEW IF EXISTS mv').materialized, true);
  const r = one('REFRESH MATERIALIZED VIEW CONCURRENTLY mv');
  assert.deepEqual([r.kind, r.concurrently], ['refresh_matview', true]);
});

test('triggers, functions, types, sequences', () => {
  const tr = one('CREATE TRIGGER trg BEFORE INSERT OR UPDATE ON public.t FOR EACH ROW EXECUTE FUNCTION fn()');
  assert.deepEqual([tr.kind, tr.name, tr.timing, tr.events.join(), tr.table.name, tr.function.name], ['create_trigger', 'trg', 'BEFORE', 'INSERT,UPDATE', 't', 'fn']);
  assert.equal(one('DROP TRIGGER IF EXISTS trg ON t').table.name, 't');
  const fn = one('CREATE OR REPLACE FUNCTION s.f(a int) RETURNS int AS $$ SELECT 1 $$ LANGUAGE sql');
  assert.deepEqual([fn.kind, fn.name.name, fn.language], ['create_function', 'f', 'sql']);
  assert.equal(one('CREATE PROCEDURE p() LANGUAGE sql AS $$ SELECT 1 $$').routine, 'procedure');
  const ty = one("CREATE TYPE mood AS ENUM ('sad', 'ok')");
  assert.deepEqual([ty.kind, ty.variant, ty.values.join()], ['create_type', 'enum', 'sad,ok']);
  const at = one("ALTER TYPE mood ADD VALUE IF NOT EXISTS 'happy' AFTER 'ok'");
  assert.deepEqual([at.kind, at.action, at.value, at.if_not_exists], ['alter_type', 'add_value', 'happy', true]);
  assert.equal(one('CREATE SEQUENCE IF NOT EXISTS s.q START 5').name.name, 'q');
});

test('destructive and maintenance statements', () => {
  assert.deepEqual(one('DROP TABLE IF EXISTS a, s.b CASCADE').tables.map((t) => t.name), ['a', 'b']);
  assert.equal(one('DROP TABLE a CASCADE').cascade, true);
  const tr = one('TRUNCATE TABLE ONLY a, b RESTART IDENTITY CASCADE');
  assert.deepEqual([tr.kind, tr.tables.length, tr.cascade], ['truncate', 2, true]);
  assert.equal(one('VACUUM FULL t').full, true);
  assert.equal(one('VACUUM (FULL, ANALYZE) t').full, true);
  assert.equal(one('VACUUM t').full, false);
  assert.deepEqual([one('CLUSTER t USING ix').kind, one('CLUSTER t USING ix').index], ['cluster', 'ix']);
});

test('grants, policies, row level security, comments', () => {
  const g = one('GRANT SELECT, INSERT ON TABLE public.orders, items TO app, ro WITH GRANT OPTION');
  assert.deepEqual([g.kind, g.privileges, g.objects.length, g.roles, g.with_grant_option], ['grant', ['SELECT', 'INSERT'], 2, ['app', 'ro'], true]);
  assert.equal(one('GRANT ALL ON ALL TABLES IN SCHEMA public TO app').all_in_schema, 'public');
  assert.equal(one('REVOKE UPDATE ON orders FROM app').kind, 'revoke');
  const p = one('CREATE POLICY tenant ON orders FOR SELECT TO app USING (tenant_id = 1)');
  assert.deepEqual([p.kind, p.name, p.table.name, p.command, p.roles], ['create_policy', 'tenant', 'orders', 'SELECT', ['app']]);
  assert.equal(one("COMMENT ON COLUMN t.c IS 'x'").kind, 'comment');
});

// ------------------------------------------------------------------ DML / SELECT

test('DML: target table and WHERE detection', () => {
  const u = one('UPDATE ONLY public.t SET a = 1');
  assert.deepEqual([u.kind, u.table.name, u.table.schema, u.has_where], ['update', 't', 'public', false]);
  assert.equal(one('UPDATE t SET a = 1 WHERE id = 2').has_where, true);
  assert.equal(one('UPDATE t SET a = (SELECT max(x) FROM u WHERE u.id = 1)').has_where, false);
  const d = one('DELETE FROM t');
  assert.deepEqual([d.kind, d.has_where], ['delete', false]);
  assert.equal(one('DELETE FROM t WHERE x < 3').has_where, true);
  const i = one('INSERT INTO t (a) SELECT x FROM u');
  assert.deepEqual([i.kind, i.table.name, i.reads.map((r) => r.name)], ['insert', 't', ['u']]);
  const m = one('MERGE INTO t USING s ON t.id = s.id WHEN MATCHED THEN UPDATE SET a = s.a');
  assert.deepEqual([m.kind, m.table.name, m.reads.map((r) => r.name)], ['merge', 't', ['s']]);
  const wd = one('WITH x AS (SELECT 1) DELETE FROM t');
  assert.deepEqual([wd.kind, wd.table.name, wd.has_where], ['delete', 't', false]);
  assert.equal(one('INSERT INTO t VALUES (1) ON CONFLICT (id) DO UPDATE SET a = 2').table.name, 't');
  const mysqlDel = one('DELETE a FROM a JOIN b ON a.id = b.id WHERE b.x = 1', { dialect: 'mysql' });
  assert.deepEqual([mysqlDel.table.name, mysqlDel.reads.map((r) => r.name)], ['a', ['a', 'b']]);
});

test('SELECT: FROM/JOIN extraction, schema-qualified names, CTEs excluded', () => {
  const st = one(`WITH recent AS (SELECT * FROM events e WHERE e.at > now()),
      big AS NOT MATERIALIZED (SELECT * FROM recent)
    SELECT * FROM recent r
      JOIN public.users u ON u.id = r.user_id
      LEFT JOIN LATERAL (SELECT 1 FROM audit.logs l WHERE l.u = u.id) x ON true
      , plain p
    WHERE EXTRACT(epoch FROM r.at) > 0`);
  assert.equal(st.kind, 'select');
  const names = st.reads.map((r) => `${r.schema ?? ''}.${r.name}`).sort();
  assert.deepEqual(names, ['.events', '.plain', 'audit.logs', 'public.users']);
  assert.deepEqual(st.ctes, ['big', 'recent']);
  assert.deepEqual(st.joins, [], 'joins against a CTE are not table joins');
  const j = one('SELECT 1 FROM a x JOIN b y ON x.id = y.id LEFT JOIN s.c ON c.id = y.id');
  assert.deepEqual(j.joins.map((p) => `${p.left.name}>${p.right.schema ?? ''}.${p.right.name}`), ['a>.b', 'b>s.c']);
});

test('extractTables: functions in FROM are not tables; IS DISTINCT FROM is ignored', () => {
  const { tables } = extractTables(tokenize('SELECT * FROM generate_series(1, 3) g, t WHERE a IS DISTINCT FROM b'));
  assert.deepEqual(tables.map((t) => t.name), ['t']);
});

test('unknown statements never throw and keep their text', () => {
  for (const sql of ['FROBNICATE the widgets', 'CALL do_things(1)', 'COPY t FROM stdin', 'EXPLAIN SELECT 1', '']) {
    assert.doesNotThrow(() => parseSql(sql));
  }
  const u = one('FROBNICATE the widgets');
  assert.equal(u.kind, 'unknown');
  assert.equal(u.text, 'FROBNICATE the widgets');
});

test('transaction control is classified', () => {
  assert.equal(one('BEGIN').kind, 'transaction');
  assert.equal(one('COMMIT').kind, 'transaction');
});

// ------------------------------------------------------------------ robustness

test('parser does not throw on 1000 random byte strings (seeded)', () => {
  const rnd = prng(0x5eed);
  const alphabet = [...'abcSELECTFROMWHERE CREATE TABLE ALTER ;,()"\'`$[]{}--/*\\\n\t.=:<>+*#@!'];
  for (let i = 0; i < 1000; i++) {
    const len = Math.floor(rnd() * 200);
    let s = '';
    for (let j = 0; j < len; j++) {
      const r = rnd();
      s += r < 0.5 ? alphabet[Math.floor(rnd() * alphabet.length)] : String.fromCharCode(Math.floor(rnd() * 256));
    }
    for (const dialect of ['postgresql', 'mysql', 'sqlite', 'tsql']) {
      assert.doesNotThrow(() => parseSql(s, { dialect }), `seed iteration ${i} (${dialect})`);
    }
  }
});

test('parser does not throw on mutated real statements', () => {
  const rnd = prng(42);
  const base = [
    'CREATE TABLE t (id int PRIMARY KEY, c varchar(10) DEFAULT now() REFERENCES u (id) ON DELETE CASCADE)',
    'ALTER TABLE t ADD COLUMN c int, ALTER COLUMN d TYPE text USING d::text, ADD CONSTRAINT k FOREIGN KEY (a) REFERENCES b NOT VALID',
    'WITH x AS (SELECT * FROM a JOIN b ON a.id = b.id) UPDATE t SET a = 1 FROM x WHERE t.id = x.id',
    'CREATE UNIQUE INDEX CONCURRENTLY i ON t USING gin (lower(a)) WHERE b > 0',
  ];
  for (let i = 0; i < 400; i++) {
    const b = base[i % base.length];
    const cut = Math.floor(rnd() * b.length);
    const mutated = rnd() < 0.5 ? b.slice(0, cut) : b.slice(0, cut) + b.slice(cut + Math.floor(rnd() * 10));
    assert.doesNotThrow(() => parseSql(mutated), mutated);
  }
});
